#!/usr/bin/env sh

loginfo() {
    printf "%s%s\n" "$logprefix" "$*" >&2
}

logwarn() {
    printf "\033[1;33m%s%s\n\033[0m" "$logprefix" "$*" >&2
}

logerr() {
    printf "\033[0;31m%s%s\n\033[0m" "$logprefix" "$*" >&2
}

logerrq() {
    logerr "$*, exiting."
    exit 1
}

setsensitivity() {
    case "$execdir" in
        "$dotdirs") sensitive=1;;
        "$dotdir" ) sensitive=0;;
        *         ) logerrq "Execution directory is incorrect";;
    esac
}

issensitive() {
    [ "$sensitive" = 1 ]
}

cdsafe() {
    cd "$*" || logerrq "Could not cd to $*"
}

lnsafe() {
    ln "$@" 2> /dev/null || sudo ln "$@" || logerr '----`ln '"$*"'` failed.'
}

mvsafe() {
    mkdir -p -- "${2%/*}"
    if mv -- "$1" "$2" 2> /dev/null; then
        ln -s -- "$3" "$1"
    elif sudo mv -- "$1" "$2"; then
        sudo ln -s -- "$3" "$1"
    else
        logerr '----`mv -- '"$*"'` failed.'
    fi
}

dotdir="$HOME/.dotfiles"
dotdirs="$HOME/.dotfiles-sensitive"
dotlistfl="dotfiles.list"
dotlistfls="dotfiles-sensitive.list"
dotlistpac="pac.list"
dotlck=".backup.lck"
execname="${0##*/}"
execdir="$(realpath -P "${0%/*}")"

setsensitivity

if issensitive; then
    mkdir -- "$dotdirs/$dotlck" || logerrq "Could not acquire lock"
    basedir="$dotdirs"
    listfl="$dotlistfls"
    listflother="$dotdir/$dotlistfl"
    logprefix="[BACKUP-SENSITIVE]: "
else
    # [ -d "$dotdirs/$dotlckdirs" ] || logerrq "Non-sensitive backup must be initiated by sensitive backup"
    mkdir -- "$dotdir/$dotlck" || logerrq "Could not acquire lock"
    basedir="$dotdir"
    listfl="$dotlistfl"
    listflother="$dotdirs/$dotlistfls"
    logprefix="[BACKUP]: "

    loginfo "Initiating sensitive backup."
    "$dotdirs/backup" || logerrq "Sensitive backup failed"
fi

cdsafe "$basedir"
pwd

[ -f "$listfl" ] || logerrq "No list file"

loginfo "Preprocessing $listfl."

sed -i "s|^~|$HOME|" -- "$listfl"
sort -V -o "$listfl" -- "$listfl"

loginfo "Parsing $listflother."
otherlist="$(xargs -r -d '\n' -n 1 realpath -P -- < "$listflother")"

loginfo "Processing $listfl."

while IFS= read -r srcfl; do
    loginfo "--Processing $srcfl."
    
    realsrcfl="$(realpath -P -- "$srcfl")"
    printf "%s\n" "$otherlist" | grep -Fxq "$realsrcfl" && logwarn "----File exists in $listflother, continuing."

    targetfl="root$srcfl"
    [ "${realsrcfl##"$basedir/"}" = "$targetfl" ] && {
        loginfo "----Nothing to do, ignoring."
        continue
    }

    realtargetfl="$(realpath -m -- "$targetfl")"
    if ! stat -- "$srcfl" > /dev/null 2>&1; then
        if [ ! -e "$targetfl" ]; then
            logwarn "----Source and target files do not exist, ignoring."
        else
            logwarn "----Source file does not exist but target does, linking."
            lnsafe -s -- "$realtargetfl" "$srcfl"
        fi
    elif [ -e "$targetfl" ]; then
        if [ ! -e "$srcfl" ]; then
            logwarn "----Source file exists but is a broken symlink, fixing."
            lnsafe -sf -- "$realtargetfl" "$srcfl"
        else
            logerr "----Source and target files exist but are not related, manual intervention needed."
        fi
    else
        logwarn "----Source file exists but target does not, moving and linking."
        mvsafe "$srcfl" "$targetfl" "$realtargetfl"
    fi
done < "$listfl"

if issensitive; then
    loginfo "Creating package list."
    if command -v pacman > /dev/null 2>&1; then
        if command -v yay > /dev/null 2>&1; then
            loginfo "--Found yay."
            yay -Q > "$dotlistpac"
        else
            loginfo "--Found pacman."
            pacman -Q > "$dotlistpac"
        fi
    else
        logwarn "Could not find pacman, aborting creation of package list."
    fi
else
    loginfo "Updating .gitignore."
    cp -f -- "$listflother" .gitignore
    printf ".gitignore\n" >> .gitignore
fi

loginfo "Recording file properties ignored by Git."

cdsafe root
find -print0 | sort -Vz | xargs -0r stat --printf='%n\0%G\0%U\0%a\0\n' -- > ../.file-properties
cdsafe ..

loginfo "Committing changes."

gitfailed=0
if git restore --staged . && sudo git add root .file-properties "$listfl" && git remote update; then
    if issensitive; then
        git add pac.list
    fi && if [ -n "$(git status -uno -s)" ]; then
        git fetch && GIT_COMMITTER_NAME="backup" GIT_COMMITTER_EMAIL="" sudo git commit --author="backup <>" -m "#$(($(git rev-list --all --count) + 1)): Automatic commit by $execname." && git push || gitfailed=1
    else
        loginfo "No changes to commit."
    fi
else
    gitfailed=1
fi

[ "$gitfailed" = "1" ] && logerr "Some Git operation(s) failed."

sudo chown -Rh "$(id -un):$(id -gn)" -- .git

loginfo "Releasing lock."

if [ -d "$basedir/$dotlck" ]; then
    rm -rf -- "$basedir/$dotlck"
else
    logwarn "Lock was forcefully released during execution."
fi

loginfo "Done."
exit 0
