#!/usr/bin/env sh

LIST="dotfiles.list"

sort -rV -o "$LIST" "$LIST" # this is crucial for the following loop if the file is a directory

while read -r i
do
    file="$( echo "$i" | sed 's/^~\///' )"
    [ -f "$file" ] && {
        rm -f "$file"
        ln -s "$file" "$HOME/$file"
        continue
    }
    [ -d "$file" ] && { 
        mv -n "$HOME/$file/"* "$file"
        ln -s "$file" "$HOME/$file"
    }
done < "$LIST"
