#!/usr/bin/env sh
# Run dotfilesbak when a dot file is modified.
# Designed to be used with cron or systemd timers.

[ "$(stat --format="%Y" -- "$HOME/.dotfiles")" -gt "$(($(date +"%s") - 7200))" ] && exec "$HOME/.dotfiles/dotfilesbak"
exit 0
