#!/usr/bin/env bash

image() {
	if [ -n "$DISPLAY" ]; then
		declare -p -A cmd=([action]=add [identifier]="PREVIEW" \
			[x]="$4" [y]="$5" [width]="$(($2-1))" [height]="$(($3-1))" [scaler]="contain" \
			[path]="$1") > "$FIFO_UEBERZUG"
		exit 1
	else
		chafa "$1" -s "${4}x${5}"
	fi
}

scope() {
	~/.config/ranger/scope.sh "$@"
}

[ -d "$XDG_CACHE_HOME/lf/preview.lck" ] && {
	scope "$@"
	exit 1
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(realpath -P -- "$1")" | sha256sum | awk '{print $1}'))"

case "$(file --mime-type --brief -- "$(realpath -P -- "$1")")" in
	application/pdf)
		[ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5"
		;;
	application/epub+zip)
		[ ! -f "$CACHE" ] && epub-thumbnailer "$1" "$CACHE" 1024
		image "$CACHE" "$2" "$3" "$4" "$5"
		;;
	video/*)
		[ ! -f "${CACHE}.jpg" ] && ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;
	image/*) image "$@";;
	*) scope "$@";;
esac
exit 0
